spring.application.name=EduFlow
spring.datasource.url=jdbc:mysql://localhost:3306/eduflow
spring.datasource.username=root
spring.datasource.password=mostafa732
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#server.port=8080

logging.level.org.springframework.security=DEBUG

# Disable template caching to see changes immediately
spring.thymeleaf.cache=false
# Enable static resource cache control
spring.web.resources.cache.period=0

jwt.secret=my-secret-key-123